monblog/urls.py
from django.conf import settings

from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path


from monblog import views as myapp_views

# from monblog.models import Article
# from monblog.models import Commentaire
from monblog.feeds import RssArticle

urlpatterns = [
    # path('admin/', admin.site.urls),
    url(r'^$', myapp_views.accueil, name='accueil'),
    url(r'^feeds/$', RssArticle()),

    url(r'^articles/', myapp_views.articles, name='articles'),
    url(r'^articles/(?P<id>\d+)$', myapp_views.lireUnArticle, name='lireUnArticle'),
    url(r'^lireUnArticle/(?P<id>\d+)$', myapp_views.lireUnArticle, name='lireUnArticle'),
    url(r'^addNewArticle/', myapp_views.addNewArticle, name='addNewArticle'),
    # url(r'^addNewCommentaire/', addNewCommentaire, name='addNewCommentaire'),

    url(r'^recherche/', myapp_views.recherche, name='recherche'),
    url(r'^contact/', myapp_views.contact, name='contact'),
    url(r'^mentionsLegales/', myapp_views.mentionsLegales, name='mentionsLegales'),

    url(r'^connexion_inscription/', myapp_views.connexion_inscription, name='connexion_inscription'),
    url(r'^connexion/', myapp_views.connexion, name='connexion'),
    url(r'^inscription/', myapp_views.inscription, name='inscription'),
    url(r'^deconnexion/', myapp_views.deconnexion, name='deconnexion'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', admin.site.urls),
]

# urlpatterns += patterns['',
#     (r'^media/(?P<path>.*)$',
#         'django.views.static.serve', {
#             'document_root': settings.MEDIA_ROOT,
#             'show_indexes': True,
#         },
#     ),
# ]

monblog/models.py
# models.py
# -*- coding: utf-8 -*-

from django.db import models


class Article(models.Model):
    titre = models.CharField(max_length=150)
    auteur = models.CharField(max_length=55)
    contenu = models.CharField(max_length=2000)
    date = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name="Date de parution")
    def __str__(self):
        return u'%s' % self.titre
    class Meta:
        ordering = ['-date']
    # def get_absolute_url(self):
    #         return ('/articles/', (), {})

class Commentaire(models.Model):
    article = models.ForeignKey('Article', on_delete=models.CASCADE)
    auteurDuCommentaire = models.CharField(max_length=55)
    texteDuCommentaire = models.CharField(max_length=500)
    dateCommentaire = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name="Date de parution")
    def __str__(self):
        return u'%s' % self.texteDuCommentaire
    class Meta:
        ordering = ['-dateCommentaire']


class Contact(models.Model):
    sujet = models.CharField(max_length=100)
    message = models.CharField(max_length=1500)
    envoyeur = models.EmailField(max_length=200)
    def __str__(self):
	    return u'%s' % self.sujet

monblog/forms.py
# forms.py
# -*- coding: utf-8 -*-

from django import forms

class ConnexionForm(forms.Form):
	username = forms.CharField(label="Nom d'utilisateur", max_length=30, widget=forms.TextInput(attrs={'placeholder': "Nom d'utilisateur"}))
	password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput(attrs={'placeholder': 'Mot de passe'}))


class ContactForm(forms.Form):
    sujet = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Sujet du mail'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Contenu de votre message...'}))
    envoyeur = forms.EmailField(label="Votre adresse mail", widget=forms.TextInput(attrs={'placeholder': 'xyz@example.com'}))
    

class AddNewArticleForm(forms.Form):
    titre = forms.CharField(max_length=150, widget=forms.TextInput(attrs={'placeholder': "Titre de l'article"}))
    contenu = forms.CharField(max_length=2000, widget=forms.Textarea(attrs={'placeholder': "Contenu de l'article..."}))


class AddNewCommentaireForm(forms.Form):
    texteDuCommentaire = forms.CharField(max_length=500, widget=forms.TextInput(attrs={'placeholder': "Laisser un commentaire"}))


class InscriptionForm(forms.Form):
    username = forms.CharField(label="Nom d'utilisateur", max_length=30, widget=forms.TextInput(attrs={'placeholder': "Nom d'utilisateur"}))
    email = forms.EmailField(label="Votre adresse mail", widget=forms.TextInput(attrs={'placeholder': 'xyz@example.com'}))
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput(attrs={'placeholder': 'Mot de passe'}))
    passwordConfirm = forms.CharField(label="Confirmation Mot de passe", widget=forms.PasswordInput(attrs={'placeholder': 'Confirmation du mot de passe'}))


choix=[('select1',"Cochez pour faire une recherche normale (titres d'article, auteurs ou contenus)"),
         ('select2','Cochez pour faire une recherche RAW SQL (une clé de tri est OBLIGATOIRE)')
      ]

choix2=[('',"Choisir (Optionnel)"),
        ('titre',"Trier les articles par titre"),
        ('auteur','Trier les articles par auteur'),
        ('contenu','Trier les articles par contenu'),
        ('date','Trier les articles par date')
      ]

class RechercheForm(forms.Form):
    recherche = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': "Article à rechercher"}))
    Type = forms.ChoiceField(choices=choix, widget=forms.RadioSelect())
    Cle = forms.ChoiceField(choices=choix2, required=False)

monblog/views.py
# views.py
# -*- coding: utf-8 -*-

from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.template import RequestContext
# from django.core.context_processors import csrf

from django.db.models import Q
from django.core.mail import EmailMessage
from django.contrib.syndication.views import Feed

from monblog.forms import ConnexionForm
from monblog.forms import InscriptionForm
from monblog.forms import ContactForm
from monblog.forms import AddNewArticleForm
from monblog.forms import AddNewCommentaireForm
from monblog.forms import RechercheForm

from monblog.models import Article
from monblog.models import Commentaire
from monblog.models import Contact


def accueil(request):
    dernierArticle = Article.objects.order_by('-date')[0]
    article_list = Article.objects.order_by('date')
    article_total = len(article_list)
    
    envoi = False
    if request.method == 'POST':
        form = AddNewCommentaireForm(request.POST) 
        if form.is_valid():
            texteDuCommentaire = form.cleaned_data['texteDuCommentaire']
            user = request.user.username
            article_id = request.POST['article_id']
            article = Article.objects.get(id=article_id)
            com = Commentaire(auteurDuCommentaire=user, texteDuCommentaire=texteDuCommentaire, article=article)
            com.save()
            form = AddNewCommentaireForm()
            envoi = True
    else: 
        form = AddNewCommentaireForm()

    user_is_logged = False
    if request.user.is_authenticated:
        user_is_logged = True
    return render(request, 'base.html', {'form': form, 'article_dernier': dernierArticle, 'total': article_total, 'les_commentaires': dernierArticle, 'user_is_logged': user_is_logged})


def articles(request):
    articles = Article.objects.order_by('-date')
    # articles = Article.objects.all()
    envoi = False
    if request.method == 'POST':
        form = AddNewCommentaireForm(request.POST) 
        if form.is_valid():
            texteDuCommentaire = form.cleaned_data['texteDuCommentaire']
            user = request.user.username
            article_id = request.POST['article_id']
            article = Article.objects.get(id=article_id)
            com = Commentaire(auteurDuCommentaire=user, texteDuCommentaire=texteDuCommentaire, article=article)
            com.save()
            form = AddNewCommentaireForm()
            envoi = True
    else: 
        form = AddNewCommentaireForm()

    user_is_logged = False
    if request.user.is_authenticated:
        user_is_logged = True
    return render(request, 'articles.html', {'form': form, 'liste_des_articles': articles, 'user_is_logged': user_is_logged})


def lireUnArticle(request, id):
    article = Article.objects.get(id=id)
    if article:
        article_exist = True
    else:
        article_exist = False
    user_is_logged = False
    if request.user.is_authenticated:
        user_is_logged = True

    envoi = False
    if request.method == 'POST':
        form = AddNewCommentaireForm(request.POST) 
        if form.is_valid():
            texteDuCommentaire = form.cleaned_data['texteDuCommentaire']
            user = request.user.username
            # article_id = request.POST['article_id']
            article = Article.objects.get(id=id)
            com = Commentaire(auteurDuCommentaire=user, texteDuCommentaire=texteDuCommentaire, article=article)
            com.save()
            form = AddNewCommentaireForm()
            envoi = True
    else: 
        form = AddNewCommentaireForm()
    return render(request, 'lireUnArticle.html', {'form': form, 'article': article, 'article_exist': article_exist, 'user_is_logged': user_is_logged})


@login_required(login_url='/connexion')
def addNewArticle(request):
    envoi = False
    if request.method == 'POST':
        form = AddNewArticleForm(request.POST) 
        if form.is_valid():
            titre = form.cleaned_data['titre']
            auteur = request.user.username
            contenu = form.cleaned_data['contenu']
            art = Article(titre=titre, auteur=auteur, contenu=contenu)
            art.save()
            form = AddNewArticleForm()
            envoi = True
    else: 
        form = AddNewArticleForm()
    user_is_logged = False
    if request.user.is_authenticated:
        user_is_logged = True
    return render(request, 'addNewArticle.html', {'form': form, 'envoi': envoi, 'user_is_logged': user_is_logged})


def recherche(request):
    user_is_logged = ''
    cleDeTri = ''
    articles = '' 
    article_total = ''
    if request.method == 'POST':  # S'il s'agit d'une requête POST
        form = RechercheForm(request.POST) 
        if form.is_valid():
            recherche = form.cleaned_data['recherche']
            Type = form.cleaned_data['Type']
            Cle = form.cleaned_data['Cle']
            if Type == 'select1':
                articles = Article.objects.filter(Q(titre__contains=recherche) | Q(auteur__contains=recherche) | Q(contenu__contains=recherche)).order_by('-date')
                article_total = len(articles)
                form = RechercheForm()
            if Type == 'select2':
                # Si l'utilisateur n'a pas choisi de clé de tri, on trie par date par défaut
                if Cle == '':
                    cleDeTri = 'date'
                else:
                    cleDeTri = Cle # Sinon on tri selon la clé renseignée par l'utilisateur
                # Maintenant ou crée la requête SQL
                debutQuery = "SELECT * FROM monblog_article"
                debutQuery += " WHERE titre LIKE " + "'%%" + recherche +  "%%'"
                debutQuery += " OR auteur LIKE " + "'%%" + recherche +  "%%'"
                debutQuery += " OR contenu LIKE " + "'%%" + recherche +  "%%'"
                debutQuery += " ORDER BY "
                finQuery = " DESC"
                articles = Article.objects.raw(debutQuery+cleDeTri+finQuery)
                # print articles.query
                article_total = len(list(articles))
                form = RechercheForm()
    else: 
        form = RechercheForm()
    if articles:
        results = True
    else:
        results = False

    user_is_logged = False
    if request.user.is_authenticated:
        user_is_logged = True
    return render(request, 'recherche.html', {'form': form, 'results': results, 'liste_des_articles': articles, 'total': article_total, 'titre': "Les articles", 'user_is_logged': user_is_logged})


def contact(request):
    envoi = False
    if request.method == 'POST':
        form = ContactForm(request.POST) 
        if form.is_valid():
            sujet = form.cleaned_data['sujet']
            message = form.cleaned_data['message']
            envoyeur = form.cleaned_data['envoyeur']
            # Nous pourrions ici envoyer l'e-mail grâce aux données que nous venons de récupérer
            contact = Contact()
            email = EmailMessage(sujet, message, envoyeur)
            email.send()
            envoi = True
            form = ContactForm()
    else: 
        form = ContactForm()
    user_is_logged = False
    if request.user.is_authenticated:
        user_is_logged = True
    return render(request, 'contact.html', {'form': form, 'envoi': envoi, 'user_is_logged': user_is_logged})


def mentionsLegales(request):
    user_is_logged = False
    if request.user.is_authenticated:
        user_is_logged = True
    return render(request, 'mentionsLegales.html', {'titre': "Les articles", 'user_is_logged': user_is_logged})


def connexion_inscription(request):
    user_is_logged = False
    if request.user.is_authenticated:
        user_is_logged = True
    return render(request, 'connexion_inscription.html', {'titre': "Page De Connexion", 'user_is_logged': user_is_logged})


def connexion(request):
    error = False
    if request.method == "POST":
        form = ConnexionForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)
            if user:  # Si l'objet renvoyé n'est pas None
                login(request, user)  # nous connectons l'utilisateur
            else: # sinon une erreur sera affichée
                error = True
    else:
        form = ConnexionForm()
    return render(request, 'connexion.html', { 'form': form, 'titre': "Page D'Inscription", 'error': error})


def inscription(request):
    if request.method == 'POST':
        form = InscriptionForm(request.POST) 
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            passwordConfirm = form.cleaned_data['passwordConfirm']
            # On crée l'utilisateur
            if password == passwordConfirm:
                user = User.objects.create_user(username=username, password=password, email=email)
                user.save()
                # envoi = True
            # else envoi = False
                user = authenticate(username=username, password=password)  # on vérifie si les données sont correctes
                if user:  # Si l'objet renvoyé n'est pas None
                    login(request, user)  # on connecte l'utilisateur
                else: # sinon une erreur sera affichée
                    error = True
    else: 
        form = InscriptionForm()  # On crée un formulaire vide
    user_is_logged = False
    if request.user.is_authenticated:
        user_is_logged = True
    return render(request, 'inscription.html', {'form': form, 'titre': "Page D'Inscription", 'user_is_logged': user_is_logged})


def deconnexion(request):
    auth.logout(request)
    request.session.flush()
    # request.user = AnonymousUser

monblog/templates/addNewArticle.html
{% extends "base.html" %}

{% block title %} Page Des Articles {% endblock title %}

{% block content %}

<div class="centered">
	<h1>Ajout d'un nouvel article</h1>
	<hr>
	{% if user.is_authenticated %}
		{% if envoi %} 
			<p> Votre nouvel article a bien été ajouté ! </p>
		{% else %}
			<form action="{% url 'addNewArticle' %}" method="post">
			    {% csrf_token %}
			    {{ form.as_p }}
			    <input type="submit" value="Ajouter" class="btn btn-primary"/>
			</form>
		{% endif %}
	{% else %}
		<p id="unknownUser">Vous devez être connecté pour pouvoir ajouter un nouvel article !</p>
	{% endif %}
</div>
{% endblock content %}

monblog/templates/articles.html
{% extends "base.html" %}

{% block title %} Page Des Articles {% endblock title %}

{% block content %}

<div class="centered">
	<h1>Les Articles</h1>
	<hr>
	<a href="/addNewArticle/"><button type="button" class="btn btn-primary">Veuillez cliquer ici pour ajouter un nouvel Article</button></a>
	<hr>
	{% for article in liste_des_articles %}
	    <div class="article">
	        <h3>Titre de l'article : {{ article.titre }}</h3>
	        <p>Auteur de l'article : {{ article.auteur }}</p>
	        <p>Date de parution : {{ article.date }}</p>
	        <p class="P_article"> Contenu de l'article :</p> 
	        <div class="contenuArticle">
	        	<p>{{ article.contenu|truncatewords_html:80 }}</p>
	        	<div align="center">
		        	<p><a href="{% url 'lireUnArticle' article.id %}" class="btn btn-success">Lire la suite</a>
		        </div>
	        </div>

	        <div class="commentaires">
			    {% if user_is_logged %}
				    <p> Les commentaires de cet articles sont :</p>
				    <form action="{% url 'articles' %}" method="post">
					    {% csrf_token %}
					    {{ form.as_p }}
					    <input type="hidden" name="article_id" value="{{ article.id }}">
					    <input type="submit" value="Commenter" class="btn btn-primary"/>
					</form>
				{% else %}
					<p id="unknownUser">Vous devez être connecté pour pouvoir commenter un article !</p>
				{% endif %}

				{% for comment in article.commentaire_set.all %}
			        <p id="auteur">Auteur : {{ comment.auteurDuCommentaire }} | {{ comment.dateCommentaire }}</p>
			        <div class="contenuCommentaire"><p>Commentaire : {{ comment.texteDuCommentaire }}</p></div>
				{% empty %}
					<p>Aucun commentaire.</p>
				{% endfor %}
			</div>
		</div>				
	{% empty %}
	    <p>Aucun article.</p>
	{% endfor %}
</div>
{% endblock content %}

monblog/templates/base.html
<!DOCTYPE html>

<html lang="fr">

<head>
    <meta name="author" content="cismael">

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '/myStyle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/bootstrap/css/bootstrap.css' %}">
   	<title>{% block title %} Bienvenu sur mon blog {% endblock title %}</title>
   	<script src='https://www.google.com/recaptcha/api.js'></script>
</head>

<body>
	<div class="well">
		<header>
			<h1>Bienvenu sur mon blog écrit en Python avec Django !!!</h1>
		</header>
		
		<div class="bouton_conn">
			{% if user.is_authenticated %}
				Bonjour, {{ user.username }} ! Vous êtes connecté.
				<a href="/deconnexion/"><button type="button" class="btn btn-primary">Déconnexion</button></a>
			{% else %}	 			
				<a href="/connexion_inscription/"><button type="button" class="btn btn-primary">Se connecter / S'inscrire</button></a>
			{% endif %}
		</div>

		<!-- Menus de navigation -->
		 <nav>
	       	<ul class="nav nav-pills nav-justified">
				<li class=""><a href="/">Accueil</a></li>
				<li class=""><a href="/articles/">Liste des articles</a></li>
				<li class=""><a href="/recherche/">Recherche</a></li>
				<li class=""><a href="/contact/">Contact</a></li>
				<li class=""><a href="/mentionsLegales/">Crédit Et Mentions Légales</a></li>
			</ul>
	   </nav>


		<section> 
	       	{% block content %}
				<div class="centered">
					<p>	
						<h1>Accueil</h1>
						{% if user.is_authenticated %}
						{% else %}	 	
							<small>Bonjour cher visiteur, veuillez vous connecter ou vous inscrire pour avoir accès à toutes les fonctionnalités du site. </small>	
						{% endif %}
						<hr>
							<ul class="nav nav-pills nav-justified">
								<li><a href="/feeds/">Flux RSS 
										{% load static %}
										<img src="{% static 'flux_rss.jpg' %}" width="35"/>
									</a>
									<!-- <img src="../media/flux_rss.jpg" width="35"></a> -->
								</li>
							</ul>
						<hr>
						<p>Il y a en tout ( {{ total }} ) article(s) publié(s) sur mon blog.</p>
						{% if article_dernier %}
							Le dernier article apparu sur mon blog est le suivant :<br>
						    <div class="article">
						        <h3>Titre de l'article : {{ article_dernier.titre }}</h3>
						        <p>Auteur de l'article : {{ article_dernier.auteur }}</p>
						        <p>Date de parution : {{ article_dernier.date }}</p>
						        <p class="P_article"> Contenu de l'article :</p> 
						        <div class="contenuArticle"> 
						        	<p>{{ article_dernier.contenu }}</p>
						        </div>

						    <div class="commentaires">						    
						    {% if user_is_logged %}
							    <p> Les commentaires de cet articles sont :</p>
							    <form action="{% url 'accueil' %}" method="post">
								    {% csrf_token %}
								    {{ form.as_p }}
								    <input type="hidden" name="article_id" value="{{ article_dernier.id }}">
								    <input type="submit" value="Commenter" class="btn btn-primary"/>
								</form>
							{% else %}
								<p id="unknownUser">Vous devez être connecté pour pouvoir commenter un article !</p>
							{% endif %}

							{% for comment in article_dernier.commentaire_set.all %}
						        <p id="auteur">Auteur : {{ comment.auteurDuCommentaire }} | {{ comment.dateCommentaire }}</p>
						        <div class="contenuCommentaire"><p id="commentaireX">Commentaire : {{ comment.texteDuCommentaire }}</p></div>
							{% empty %}
								<p>Aucun commentaire.</p>
							{% endfor %}
						</div>
						{% else %}
						    <p>Aucun article.</p>
						{% endif %}
					</p>
				</div>
			{% endblock content %}
	   	</section>


		<footer>
			<p> &copy; - cismael - 2015 - <a href="/mentionsLegales/">Crédit Et Mentions Légales <a/> </p>
		</footer>
	</div>
</body>

</html>

monblog/templates/connexion.html
{% extends "base.html" %}

{% block title %} {{ titre }} {% endblock title %}

{% block content %}
 <div class="centered">
 	<h3>Page De Connexion</h3>
	<hr>
	{% if error %}
		<p id="unknownUser"><strong>Utilisateur inconnu ou mauvais mot de passe.</strong></p>
	{% endif %}
	{% if user.is_authenticated %}
		Bonjour, {{ user.username }} ! Vous êtes connecté.
	{% else %}
		<form action="{% url 'connexion' %}" method="post">
		    {% csrf_token %}
		    {{ form.as_p }}
		    <input type="submit" value="Se connecter" class="btn btn-primary"/>
		</form>
	{% endif %}
</div>
{% endblock content %}

monblog/templates/connexion_inscription.html
{% extends "base.html" %}

{% block title %} Page De Contact {% endblock title %}

{% block content %}
 <div class="centered">
 	<h3>Connexion / Inscription</h3>
	<hr>
	<form id='connexion_inscription' method="post" action="#" style="display:inline;">
		<p>
			<a href="/connexion/" class="btn btn-primary">Vous avez déjà un compte ? <br> Connexion"</a>
			<a href="/inscription/" class="btn btn-primary">Vous n'avez pas encore de compte ? <br> Inscription"</a>
		</p>
	</form>
</div>
{% endblock content %}

monblog/templates/contact.html
{% extends "base.html" %}

{% block title %} Page De Contact {% endblock title %}

{% block content %}
 <div class="centered">
	<h3>FORMULAIRE DE CONTACT</h3>
	<hr>
	{% if envoi %}
		<p id="success">Votre message a bien été envoyé ! </p>
	{% endif %}
	<form action="{% url 'contact' %}" method="post">
	    {% csrf_token %}
	    {{ form.as_p }}
	    <div class="g-recaptcha" data-sitekey="6Lc_XAATAAAAAGMLJSuX5p8eg4OM8P8hUmxS6hLZ" align="center"></div>
	    <input type="submit" value="Envoyer" class="btn btn-primary"/>
	</form>	
</div>
{% endblock content %}

monblog/templates/inscription.html
{% extends "base.html" %}

{% block title %} Page De Contact {% endblock title %}

{% block content %}
 <div class="centered">
 	<h3>Page D'Inscription</h3>
	<hr>
	{% if error %}
	<p><strong>Utilisateur inconnu ou mauvais de mot de passe.</strong></p>
	{% endif %}
	{% if user.is_authenticated %}
		Bonjour, {{ user.username }} ! Vous êtes connecté.
	{% else %}

	<form action="{% url 'inscription' %}" method="post">
	    {% csrf_token %}
	    {{ form.as_p }}
	    <input type="submit" value="Se connecter" class="btn btn-primary"/>
	</form>
	{% endif %}
</div>
{% endblock content %}

monblog/templates/lireUnArticle.html
{% extends "base.html" %}

{% block title %} Page De Vue D'Un Seul Article {% endblock title %}

{% block content %}
<div class="centered">
	<h1>Lecture D'Un Article Unique</h1>
	<hr>
	{% if article_exist %}
	    <div class="article">
	        <h3>Titre de l'article : {{ article.titre }}</h3>
	        <p>Auteur de l'article : {{ article.auteur }}</p>
	        <p>Date de parution : {{ article.date }}</p>
	        <p class="P_article"> Contenu de l'article :</p> 
	        <div class="contenuArticle"> 
	        	<p>{{ article.contenu }}</p>
	        </div>

		 <div class="commentaires">
		    {% if user_is_logged %}
		    <p> Les commentaires de cet articles sont :</p>
		    <form action="{% url 'lireUnArticle' article.id %}" method="post">
			    {% csrf_token %}
			    {{ form.as_p }}
			    <!-- <input type="hidden" name="article_id" value="{{ article.id }}"> -->
			    <input type="submit" value="Commenter" class="btn btn-primary"/>
			</form>
			{% else %}
				<p id="unknownUser">Vous devez être connecté pour pouvoir commenter un article !</p>
			{% endif %}

			{% for comment in article.commentaire_set.all %}
		        <p id="auteur">Auteur : {{ comment.auteurDuCommentaire }} | {{ comment.dateCommentaire }}</p>
		        <div class="contenuCommentaire"><p>Commentaire : {{ comment.texteDuCommentaire }}</p></div>
			{% empty %}
				<p>Aucun commentaire.</p>
			{% endfor %}
		</div>
	{% else %}
		<p>Aucun article.</p>
	{% endif %}
</div>
{% endblock content %}

monblog/templates/recherche.html
{% extends "base.html" %}

{% block title %} Page De Recherche {% endblock title %}

{% block content %}
<div class="centered">
	<h1>Recherche</h1>
	<hr>
	<p>Saisissez un auteur, un titre ou un mot à rechercher dans le contenu d'un article</p>
	<form action="{% url 'recherche' %}" method="post">
	    {% csrf_token %}
	    {{ form.as_p }}
	    <input type="submit" value="Search" class="btn btn-primary"/>
	</form>
	<hr>
	{% if results %}
		<p>Résultat(s) de la recherche : [ {{ total }} ] article(s) trouvé(s).</p>
	{% endif %}
	{% for article in liste_des_articles %}
    <div class="article">
        <h3>Titre de l'article : {{ article.titre }}</h3>
        <p>Auteur de l'article : {{ article.auteur }}</p>
        <p>Date de parution : {{ article.date }}</p>
        <p class="P_article"> Contenu de l'article :</p> 
        <div class="contenuArticle"> 
        	<!-- <p>{{ article.contenu }}</p> -->
        	<p>{{ article.contenu|truncatewords_html:80 }}</p>
        	<div align="center">
	        	<p><a href="{% url 'lireUnArticle' article.id %}" class="btn btn-success">Lire la suite</a>
	        </div>
        </div>

        <div class="commentaires">
		    {% if user.is_authenticated %}
			    <p> Les commentaires de cet articles sont :</p>
			{% else %}
				<p id="unknownUser">Vous devez être connecté pour pouvoir commenter un article !</p>
			{% endif %}

			{% for comment in article.commentaire_set.all %} 
		        <p id="auteur">Auteur : {{ comment.auteurDuCommentaire }} | {{ comment.dateCommentaire }}</p>
		        <div class="contenuCommentaire"><p id="commentaireX">Commentaire : {{ comment.texteDuCommentaire }}</p></div>
			{% empty %}
				<p>Aucun commentaire.</p>
			{% endfor %}
		</div>
	</div>				
	{% empty %}
	    <p>Aucun article.</p>
	{% endfor %}
	</div>
{% endblock content %}